# Simulated daily request to your render project so that the service doesn't go down
name: Daily render ping

on:
  schedule:
    - cron: '*/20 * * * *' 
  workflow_dispatch: 

jobs:
  curl-website:
    runs-on: ubuntu-latest

    steps:
      - name: Run cURL on Website
        run: curl -I https://mini-kanban-brand.onrender.com
